/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctomap */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctomap
#define _Included_es_usc_citius_lab_joctomap_JOctomap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_JOctomap
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_JOctomap_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
