/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctree */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctree
#define _Included_es_usc_citius_lab_joctomap_JOctree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    write
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_es_usc_citius_lab_joctomap_JOctree_write
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    read
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_es_usc_citius_lab_joctomap_JOctree_read
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
