/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_util_AdjacencyMap */

#ifndef _Included_es_usc_citius_lab_joctomap_util_AdjacencyMap
#define _Included_es_usc_citius_lab_joctomap_util_AdjacencyMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_util_AdjacencyMap
 * Method:    initializeJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_util_AdjacencyMap_initializeJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
