/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctreeKey */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctreeKey
#define _Included_es_usc_citius_lab_joctomap_JOctreeKey
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
