/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap */

#ifndef _Included_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
#define _Included_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_update
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    getDistance
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_getDistance__DDD
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    getDistance
 * Signature: (Les/usc/citius/lab/joctomap/octree/JOctreeKey;)D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_getDistance__Les_usc_citius_lab_joctomap_octree_JOctreeKey_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    getDistanceAndClosestObstacle
 * Signature: (DDD)Les/usc/citius/lab/joctomap/util/Obstacle;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_getDistanceAndClosestObstacle
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    create
 * Signature: (Les/usc/citius/lab/joctomap/octree/JOctree;D)Les/usc/citius/lab/joctomap/distance/JOctreeDistanceMap;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_create
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_distance_JOctreeDistanceMap_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
