/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctree */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctree
#define _Included_es_usc_citius_lab_joctomap_JOctree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    cellKeyAt
 * Signature: (FFF)Les/usc/citius/lab/joctomap/JOctreeKey;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_JOctree_cellKeyAt__FFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    cellKeyAt
 * Signature: (FFFI)Les/usc/citius/lab/joctomap/JOctreeKey;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_JOctree_cellKeyAt__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    adjustKeyAt
 * Signature: (Les/usc/citius/lab/joctomap/JOctreeKey;I)Les/usc/citius/lab/joctomap/JOctreeKey;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_JOctree_adjustKeyAt
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    getTreeDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_usc_citius_lab_joctomap_JOctree_getTreeDepth
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    getResolution
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_JOctree_getResolution
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    getNodeSize
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_JOctree_getNodeSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    write
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_es_usc_citius_lab_joctomap_JOctree_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    read
 * Signature: (Ljava/lang/String;)Les/usc/citius/lab/joctomap/JOctree;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_JOctree_read
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
