/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctree */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctree
#define _Included_es_usc_citius_lab_joctomap_JOctree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    cellKeyAt
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_JOctree_cellKeyAt__FFF
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    cellKeyAt
 * Signature: (FFFI)V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_JOctree_cellKeyAt__FFFI
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jint);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    write
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_es_usc_citius_lab_joctomap_JOctree_write
  (JNIEnv *, jobject, jstring);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctree
 * Method:    read
 * Signature: (Ljava/lang/String;)Les/usc/citius/lab/joctomap/JOctree;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_JOctree_read
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
