/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_JOctreeNode */

#ifndef _Included_es_usc_citius_lab_joctomap_JOctreeNode
#define _Included_es_usc_citius_lab_joctomap_JOctreeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_JOctreeNode
 * Method:    getOccupancy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_JOctreeNode_getOccupancy
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_JOctreeNode
 * Method:    getValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_es_usc_citius_lab_joctomap_JOctreeNode_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
