/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_iterators_LeafBBXIterator */

#ifndef _Included_es_usc_citius_lab_joctomap_iterators_LeafBBXIterator
#define _Included_es_usc_citius_lab_joctomap_iterators_LeafBBXIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_iterators_LeafBBXIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_es_usc_citius_lab_joctomap_iterators_LeafBBXIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_iterators_LeafBBXIterator
 * Method:    next
 * Signature: ()Les/usc/citius/lab/joctomap/octree/JOctreeKey;
 */
JNIEXPORT jobject JNICALL Java_es_usc_citius_lab_joctomap_iterators_LeafBBXIterator_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
