/**
 * Copyright (C) 2014-2017 Adrián González Sieira (adrian.gonzalez@usc.es)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_util_AdjacencyMap */

#ifndef _Included_es_usc_citius_lab_joctomap_util_AdjacencyMap
#define _Included_es_usc_citius_lab_joctomap_util_AdjacencyMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_util_AdjacencyMap
 * Method:    initializeJNI
 * Signature: (Les/usc/citius/lab/joctomap/octree/JOctree;)V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_util_AdjacencyMap_initializeJNI
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
