/**
 * Copyright (C) 2014-2017 Adrián González Sieira (adrian.gonzalez@usc.es)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_usc_citius_lab_joctomap_octree_JOctreeNode */

#ifndef _Included_es_usc_citius_lab_joctomap_octree_JOctreeNode
#define _Included_es_usc_citius_lab_joctomap_octree_JOctreeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_usc_citius_lab_joctomap_octree_JOctreeNode
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_usc_citius_lab_joctomap_octree_JOctreeNode_dispose
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_octree_JOctreeNode
 * Method:    getOccupancy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_es_usc_citius_lab_joctomap_octree_JOctreeNode_getOccupancy
  (JNIEnv *, jobject);

/*
 * Class:     es_usc_citius_lab_joctomap_octree_JOctreeNode
 * Method:    getValue
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_es_usc_citius_lab_joctomap_octree_JOctreeNode_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
